# 第3章 大規模言語モデルの基礎
## 3.2 GPT (デコーダ)

In [1]:
# GPT
from transformers import pipeline

generator = pipeline(
    "text-generation", model="abeja/gpt2-large-japanese"
)
outputs = generator("日本で一番高い山は")
print(outputs[0]["generated_text"])

/Users/ysumita/work/python/llm-book/.venv/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
You are using the default legacy behaviour of the <class 'transformers.models.t5.tokenization_t5.T5Tokenizer'>. This is expected, and simply means that the `legacy` (previous) behavior will be used so nothing changes for you. If you want to use the new behaviour, set `legacy=False`. This should only be set if you understand what it means, and thoroughly read the reason why this was added as explained in https://github.com/huggingface/transformers/pull/24565
/Users/ysumita/work/python/llm-book/.venv/lib/python3.10/site-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(
Hardware accelerator e.g. GPU is available in the environment, but no `device` argument is passed to the `Pipeline` object. Model will be on CPU.

日本で一番高い山は標高1,776m、日本最高峰の山です。 冬になると氷点下の極寒地帯は マイナス50度にもなるという 厳しい気候を誇り... みなさんは 自分のお家

## 3.3 BERT・RoBERTa (エンコーダ)

In [2]:
# BERT
import pandas as pd

fill_mask = pipeline("fill-mask", model="cl-tohoku/bert-base-japanese-v3")

masked_text = "日本の首都は[MASK]である"
outputs = fill_mask(masked_text)
display(pd.DataFrame(outputs[:3]))

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
/Users/ysumita/work/python/llm-book/.venv/lib/python3.10/site-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(
Hardware accelerator e.g. GPU is available in the environment, but no `device` argument is passed to the `Pipeline` object. Model will be on CPU.

      score  token token_str           sequence
0  0.884172  12569        東京  日本 の 首都 は 東京 で ある
1  0.024820  12759        大阪  日本 の 首都 は 大阪 で ある
2  0.020863  13017        京都  日本 の 首都 は 京都 で ある

In [3]:
masked_text = "今日の映画は刺激的で面白かった。この映画は[MASK]。"
outputs = fill_mask(masked_text)
display(pd.DataFrame(outputs[:3]))

      score  token token_str                                   sequence
0  0.683932  23845     素晴らしい  今日 の 映画 は 刺激 的 で 面白かっ た 。 この 映画 は 素晴らしい 。
1  0.101234  24683       面白い    今日 の 映画 は 刺激 的 で 面白かっ た 。 この 映画 は 面白い 。
2  0.048003  26840       楽しい    今日 の 映画 は 刺激 的 で 面白かっ た 。 この 映画 は 楽しい 。